In [3]:
!pip install numpy
!pip install pandas
!pip install scikit-learn

In [4]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [5]:
df = pd.read_csv("heart.csv")

In [9]:
df.head()

Age Gender ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0   40      M           ATA        140          289          0     Normal   
1   49      F           NAP        160          180          0     Normal   
2   37      M           ATA        130          283          0         ST   
3   48      F           ASY        138          214          0     Normal   
4   54      M           NAP        150          195          0     Normal   

   MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0    172              N      0.0       Up             0  
1    156              N      1.0     Flat             1  
2     98              N      0.0       Up             0  
3    108              Y      1.5     Flat             1  
4    122              N      0.0       Up             0

In [8]:
df.tail()

Age Gender ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
913   45      M            TA        110          264          0     Normal   
914   68      M           ASY        144          193          1     Normal   
915   57      M           ASY        130          131          0     Normal   
916   57      F           ATA        130          236          0        LVH   
917   38      M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0

In [19]:
df.dtypes

Age                 int64
Gender             object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object

In [20]:
df["Gender"].unique()

array(['M', 'F'], dtype=object)

In [21]:
df["ChestPainType"].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [22]:
df["RestingECG"].unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [23]:
ohe = OneHotEncoder()

In [24]:
print(ohe)

OneHotEncoder()


In [25]:
ohe.fit_transform(df[["Gender", "ChestPainType", "RestingECG"]]).toarray()

array([[0., 1., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [26]:
#saved array result
feature_array = ohe.fit_transform(df[["Gender", "ChestPainType", "RestingECG"]]).toarray()

In [28]:
print(feature_array)

[[0. 1. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 1.]
 ...
 [0. 1. 1. ... 0. 1. 0.]
 [1. 0. 0. ... 1. 0. 0.]
 [0. 1. 0. ... 0. 1. 0.]]


In [30]:
ohe.categories_

[array(['F', 'M'], dtype=object),
 array(['ASY', 'ATA', 'NAP', 'TA'], dtype=object),
 array(['LVH', 'Normal', 'ST'], dtype=object)]

In [31]:
#saved categories as feature_labels
feature_labels = ohe.categories_

In [34]:
#convert arrays in one array
combined_array = np.concatenate((feature_labels))

In [35]:
print(combined_array)

['F' 'M' 'ASY' 'ATA' 'NAP' 'TA' 'LVH' 'Normal' 'ST']


In [36]:
pd.DataFrame(feature_array, columns = combined_array)

F    M  ASY  ATA  NAP   TA  LVH  Normal   ST
0    0.0  1.0  0.0  1.0  0.0  0.0  0.0     1.0  0.0
1    1.0  0.0  0.0  0.0  1.0  0.0  0.0     1.0  0.0
2    0.0  1.0  0.0  1.0  0.0  0.0  0.0     0.0  1.0
3    1.0  0.0  1.0  0.0  0.0  0.0  0.0     1.0  0.0
4    0.0  1.0  0.0  0.0  1.0  0.0  0.0     1.0  0.0
..   ...  ...  ...  ...  ...  ...  ...     ...  ...
913  0.0  1.0  0.0  0.0  0.0  1.0  0.0     1.0  0.0
914  0.0  1.0  1.0  0.0  0.0  0.0  0.0     1.0  0.0
915  0.0  1.0  1.0  0.0  0.0  0.0  0.0     1.0  0.0
916  1.0  0.0  0.0  1.0  0.0  0.0  1.0     0.0  0.0
917  0.0  1.0  0.0  0.0  1.0  0.0  0.0     1.0  0.0

[918 rows x 9 columns]

In [37]:
#saved results in features
features = pd.DataFrame(feature_array, columns = combined_array)

In [38]:
print(features)

       F    M  ASY  ATA  NAP   TA  LVH  Normal   ST
0    0.0  1.0  0.0  1.0  0.0  0.0  0.0     1.0  0.0
1    1.0  0.0  0.0  0.0  1.0  0.0  0.0     1.0  0.0
2    0.0  1.0  0.0  1.0  0.0  0.0  0.0     0.0  1.0
3    1.0  0.0  1.0  0.0  0.0  0.0  0.0     1.0  0.0
4    0.0  1.0  0.0  0.0  1.0  0.0  0.0     1.0  0.0
..   ...  ...  ...  ...  ...  ...  ...     ...  ...
913  0.0  1.0  0.0  0.0  0.0  1.0  0.0     1.0  0.0
914  0.0  1.0  1.0  0.0  0.0  0.0  0.0     1.0  0.0
915  0.0  1.0  1.0  0.0  0.0  0.0  0.0     1.0  0.0
916  1.0  0.0  0.0  1.0  0.0  0.0  1.0     0.0  0.0
917  0.0  1.0  0.0  0.0  1.0  0.0  0.0     1.0  0.0

[918 rows x 9 columns]


In [39]:
features.head()

F    M  ASY  ATA  NAP   TA  LVH  Normal   ST
0  0.0  1.0  0.0  1.0  0.0  0.0  0.0     1.0  0.0
1  1.0  0.0  0.0  0.0  1.0  0.0  0.0     1.0  0.0
2  0.0  1.0  0.0  1.0  0.0  0.0  0.0     0.0  1.0
3  1.0  0.0  1.0  0.0  0.0  0.0  0.0     1.0  0.0
4  0.0  1.0  0.0  0.0  1.0  0.0  0.0     1.0  0.0

In [40]:
pd.concat([df, features], axis=1)

Age Gender ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40      M           ATA        140          289          0     Normal   
1     49      F           NAP        160          180          0     Normal   
2     37      M           ATA        130          283          0         ST   
3     48      F           ASY        138          214          0     Normal   
4     54      M           NAP        150          195          0     Normal   
..   ...    ...           ...        ...          ...        ...        ...   
913   45      M            TA        110          264          0     Normal   
914   68      M           ASY        144          193          1     Normal   
915   57      M           ASY        130          131          0     Normal   
916   57      F           ATA        130          236          0        LVH   
917   38      M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak  ... HeartDisease    F    M  ASY  ATA  NAP  \
0      172              N      0.0  ...            0  0.0  1.0  0.0  1.0  0.0   
1      156              N      1.0  ...            1  1.0  0.0  0.0  0.0  1.0   
2       98              N      0.0  ...            0  0.0  1.0  0.0  1.0  0.0   
3      108              Y      1.5  ...            1  1.0  0.0  1.0  0.0  0.0   
4      122              N      0.0  ...            0  0.0  1.0  0.0  0.0  1.0   
..     ...            ...      ...  ...          ...  ...  ...  ...  ...  ...   
913    132              N      1.2  ...            1  0.0  1.0  0.0  0.0  0.0   
914    141              N      3.4  ...            1  0.0  1.0  1.0  0.0  0.0   
915    115              Y      1.2  ...            1  0.0  1.0  1.0  0.0  0.0   
916    174              N      0.0  ...            1  1.0  0.0  0.0  1.0  0.0   
917    173              N      0.0  ...            0  0.0  1.0  0.0  0.0  1.0   

      TA  LVH  Normal   ST  
0    0.0  0.0     1.0  0.0  
1    0.0  0.0     1.0  0.0  
2    0.0  0.0     0.0  1.0  
3    0.0  0.0     1.0  0.0  
4    0.0  0.0     1.0  0.0  
..   ...  ...     ...  ...  
913  1.0  0.0     1.0  0.0  
914  0.0  0.0     1.0  0.0  
915  0.0  0.0     1.0  0.0  
916  0.0  1.0     0.0  0.0  
917  0.0  0.0     1.0  0.0  

[918 rows x 21 columns]

In [41]:
#real data with one hot encoding data in df_new
df_new = pd.concat([df, features], axis=1)

In [42]:
df_new.head()

Age Gender ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0   40      M           ATA        140          289          0     Normal   
1   49      F           NAP        160          180          0     Normal   
2   37      M           ATA        130          283          0         ST   
3   48      F           ASY        138          214          0     Normal   
4   54      M           NAP        150          195          0     Normal   

   MaxHR ExerciseAngina  Oldpeak  ... HeartDisease    F    M  ASY  ATA  NAP  \
0    172              N      0.0  ...            0  0.0  1.0  0.0  1.0  0.0   
1    156              N      1.0  ...            1  1.0  0.0  0.0  0.0  1.0   
2     98              N      0.0  ...            0  0.0  1.0  0.0  1.0  0.0   
3    108              Y      1.5  ...            1  1.0  0.0  1.0  0.0  0.0   
4    122              N      0.0  ...            0  0.0  1.0  0.0  0.0  1.0   

    TA  LVH  Normal   ST  
0  0.0  0.0     1.0  0.0  
1  0.0  0.0     1.0  0.0  
2  0.0  0.0     0.0  1.0  
3  0.0  0.0     1.0  0.0  
4  0.0  0.0     1.0  0.0  

[5 rows x 21 columns]

In [10]:
#Label encoding
df.head(2)

Age Gender ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0   40      M           ATA        140          289          0     Normal   
1   49      F           NAP        160          180          0     Normal   

   MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0    172              N      0.0       Up             0  
1    156              N      1.0     Flat             1